### ISSUE TITLE
We need nodemailer package to our repository

### ISSUE THREAD

**Issue by R-Ayush777** [developer-student-clubs/npmBox#13]
### *nodemailer* -> https://www.npmjs.com/package/nodemailer
- Create a .js file with the name of the module and write a well commented code
- Write a documentation for the module that you have demonstrated in README.md file

**Comment by BhavinSonagara** [comment]
can you assign this issue to me

**Comment by R-Ayush777** [comment]
Sure @BhavinSonagara you can start working on it!

**Comment by R-Ayush777** [comment]
DONE ✅
