### ISSUE TITLE
We need Cloudinary Node SDK tool to our repository

### ISSUE THREAD

**Issue by R-Ayush777** [developer-student-clubs/npmBox#16]
### *cloudinary* -> https://www.npmjs.com/package/cloudinary
- Create a .js file with the name of the module and write a well commented code
- As it is SDK write code that showcase how to use it, use-cases, feature of it.
- Write a documentation for the module that you have demonstrated in README.md file

**Comment by BhavinSonagara** [comment]
Can i work on this issue ?

**Comment by R-Ayush777** [comment]
Sure!!

**Comment by R-Ayush777** [comment]
DONE
