### ISSUE TITLE
Update npm packages list

### ISSUE THREAD

**Issue by Aryan9592** [developer-student-clubs/npmBox#84]
Just update the npm packages list in [here](https://github.com/developer-student-clubs/npmBox#npm-packages-list-).
Better include both links, the one which refers to the original `npm` module, and add `docs` link if available.

**Comment by Aryan9592** [comment]
@neer-patel-11 It's better we keep it open

**Comment by neer-patel-11** [comment]
Sure

**Comment by Yash-Ainapure** [comment]
Heyy there,I would like to contribute here and started working on it.

**Comment by Aryan9592** [comment]
That's appreciated!
